numstudents1 = int(input(""))
desks1 = (numstudents1 // 2) + (numstudents1 % 2)
numstudents2 = int(input(""))
desks2 = (numstudents2 // 2) + (numstudents2 % 2)
numstudents3 = int(input(""))
desks3 = (numstudents3 // 2) + (numstudents3 % 2)
print(desks1 + desks2 + desks3)
